version: '3.8'
services:
  orquestador:
    #build: .
    image: jairocatacora/api-orquestador:2.0.1
    ports:
      - "4000:4000" 
    networks:
      - api-network

networks:
  api-network:
    driver: bridge